version: '3'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    ports:
      - 3306:3306
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=coucou42
      - MYSQL_PASSWORD=coucou42
      - MYSQL_USER=dbadmin

  